App\Entity\Laboratorium:
  type: entity
  name: laboratorium
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  oneToOne:
    idUser:
      targetEntity: User
      joinColumn:
        name: id_user
        referencedColumnName: id
  fields:
    namaLab:
      type: string
      length: 255
    jenisLab:
      type: integer
      length: 10