App\Entity\Transaksi:
  type: entity
  name: transaksi
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  oneToOne:
    idSampel:
      targetEntity: Sampel
      joinColumn:
        name: id_sampel
        referencedColumnName: id
    idHasil:
      targetEntity: Hasil
      joinColumn:
        name: id_hasil
        referencedColumnName: id
  manyToOne:
    idPelanggan:
      targetEntity: Pelanggan
      joinColumn:
        name: id_pelanggan
        referencedColumnName: id
  fields:
    biaya:
      type: integer
      length: 100
    tanggalPengambilanHasil:
      type: datetime
      name: tanggal_pengambilan_hasil